-- Customize the email verification template
UPDATE auth.users
SET raw_app_meta_data = jsonb_set(
  raw_app_meta_data,
  '{email_template_confirm_signup}',
  $template$
  {
    "subject": "Welcome to Tabi - Verify Your Email",
    "html": "<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Verify Your Email</title><style>body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1f2937; margin: 0; padding: 0; background-color: #f9fafb; } .container { max-width: 600px; margin: 0 auto; padding: 40px 20px; } .header { text-align: center; padding: 20px 0; } .logo { max-width: 120px; } .content { background: #ffffff; padding: 40px; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); } .title { font-size: 24px; font-weight: 700; color: #1f2937; margin-bottom: 24px; background: linear-gradient(to right, #2563eb, #0ea5e9); -webkit-background-clip: text; -webkit-text-fill-color: transparent; } .button { display: inline-block; background: linear-gradient(to right, #2563eb, #0ea5e9); color: white; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; margin: 24px 0; box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.2); transition: all 0.2s ease; } .button:hover { transform: translateY(-1px); box-shadow: 0 6px 8px -1px rgba(37, 99, 235, 0.3); } .text { color: #4b5563; font-size: 16px; margin-bottom: 16px; } .footer { text-align: center; padding: 24px; color: #6b7280; font-size: 14px; } .security-note { background-color: #f3f4f6; padding: 16px; border-radius: 8px; margin: 24px 0; font-size: 14px; color: #4b5563; } .divider { height: 1px; background-color: #e5e7eb; margin: 24px 0; }</style></head><body><div class='container'><div class='header'><img src='https://tabi.com/logo.png' alt='Tabi' class='logo'></div><div class='content'><h1 class='title'>Welcome to Tabi</h1><p class='text'>Thank you for joining Tabi! We're excited to have you on board. To get started, please verify your email address by clicking the button below:</p><p style='text-align: center;'><a href='{{ .ConfirmationURL }}' class='button'>Verify Email Address</a></p><div class='security-note'><strong>Security Note:</strong> If you did not create an account with Tabi, you can safely ignore this email. This verification link will expire in 24 hours.</div><div class='divider'></div><p class='text'>Once verified, you'll have full access to all Tabi features, including:</p><ul style='color: #4b5563; margin-bottom: 24px;'><li>Secure payment processing</li><li>Real-time transaction tracking</li><li>Wallet integration</li><li>And much more!</li></ul></div><div class='footer'><p>© 2024 Tabi. All rights reserved.</p><p style='margin-top: 8px;'>Questions? Contact our support team at support@tabi.com</p></div></div></body></html>",
    "text": "Welcome to Tabi!\n\nThank you for joining Tabi! We're excited to have you on board. To get started, please verify your email address by clicking the link below:\n\n{{ .ConfirmationURL }}\n\nSecurity Note: If you did not create an account with Tabi, you can safely ignore this email. This verification link will expire in 24 hours.\n\nOnce verified, you'll have full access to all Tabi features, including:\n- Secure payment processing\n- Real-time transaction tracking\n- Wallet integration\n- And much more!\n\n© 2024 Tabi. All rights reserved.\nQuestions? Contact our support team at support@tabi.com"
  }
  $template$::jsonb
); 